// Code generated by protoc-gen-go. DO NOT EDIT.
// source: reportcomm/report.proto

package reportcomm

import (
	context "context"
	fmt "fmt"
	activitycomm "github.com/FrancescoIlario/usplay/pkg/services/activitycomm"
	proto "github.com/golang/protobuf/proto"
	timestamp "github.com/golang/protobuf/ptypes/timestamp"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// The request message containing the report details
type CreateReportRequest struct {
	Name                 string    `protobuf:"bytes,1,opt,name=Name,proto3" json:"Name,omitempty"`
	Period               *Interval `protobuf:"bytes,2,opt,name=Period,proto3" json:"Period,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *CreateReportRequest) Reset()         { *m = CreateReportRequest{} }
func (m *CreateReportRequest) String() string { return proto.CompactTextString(m) }
func (*CreateReportRequest) ProtoMessage()    {}
func (*CreateReportRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_b0d9a2e7955692ed, []int{0}
}

func (m *CreateReportRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateReportRequest.Unmarshal(m, b)
}
func (m *CreateReportRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateReportRequest.Marshal(b, m, deterministic)
}
func (m *CreateReportRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateReportRequest.Merge(m, src)
}
func (m *CreateReportRequest) XXX_Size() int {
	return xxx_messageInfo_CreateReportRequest.Size(m)
}
func (m *CreateReportRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateReportRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CreateReportRequest proto.InternalMessageInfo

func (m *CreateReportRequest) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *CreateReportRequest) GetPeriod() *Interval {
	if m != nil {
		return m.Period
	}
	return nil
}

// The response message containing the id of the report
type CreateReportReply struct {
	Id                   string   `protobuf:"bytes,1,opt,name=Id,proto3" json:"Id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateReportReply) Reset()         { *m = CreateReportReply{} }
func (m *CreateReportReply) String() string { return proto.CompactTextString(m) }
func (*CreateReportReply) ProtoMessage()    {}
func (*CreateReportReply) Descriptor() ([]byte, []int) {
	return fileDescriptor_b0d9a2e7955692ed, []int{1}
}

func (m *CreateReportReply) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateReportReply.Unmarshal(m, b)
}
func (m *CreateReportReply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateReportReply.Marshal(b, m, deterministic)
}
func (m *CreateReportReply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateReportReply.Merge(m, src)
}
func (m *CreateReportReply) XXX_Size() int {
	return xxx_messageInfo_CreateReportReply.Size(m)
}
func (m *CreateReportReply) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateReportReply.DiscardUnknown(m)
}

var xxx_messageInfo_CreateReportReply proto.InternalMessageInfo

func (m *CreateReportReply) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

// The request message for the read request
type ReadReportRequest struct {
	Id                   string   `protobuf:"bytes,1,opt,name=Id,proto3" json:"Id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ReadReportRequest) Reset()         { *m = ReadReportRequest{} }
func (m *ReadReportRequest) String() string { return proto.CompactTextString(m) }
func (*ReadReportRequest) ProtoMessage()    {}
func (*ReadReportRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_b0d9a2e7955692ed, []int{2}
}

func (m *ReadReportRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ReadReportRequest.Unmarshal(m, b)
}
func (m *ReadReportRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ReadReportRequest.Marshal(b, m, deterministic)
}
func (m *ReadReportRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ReadReportRequest.Merge(m, src)
}
func (m *ReadReportRequest) XXX_Size() int {
	return xxx_messageInfo_ReadReportRequest.Size(m)
}
func (m *ReadReportRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ReadReportRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ReadReportRequest proto.InternalMessageInfo

func (m *ReadReportRequest) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

// The response message to the read request
type ReadReportReply struct {
	Report               *Report  `protobuf:"bytes,1,opt,name=report,proto3" json:"report,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ReadReportReply) Reset()         { *m = ReadReportReply{} }
func (m *ReadReportReply) String() string { return proto.CompactTextString(m) }
func (*ReadReportReply) ProtoMessage()    {}
func (*ReadReportReply) Descriptor() ([]byte, []int) {
	return fileDescriptor_b0d9a2e7955692ed, []int{3}
}

func (m *ReadReportReply) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ReadReportReply.Unmarshal(m, b)
}
func (m *ReadReportReply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ReadReportReply.Marshal(b, m, deterministic)
}
func (m *ReadReportReply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ReadReportReply.Merge(m, src)
}
func (m *ReadReportReply) XXX_Size() int {
	return xxx_messageInfo_ReadReportReply.Size(m)
}
func (m *ReadReportReply) XXX_DiscardUnknown() {
	xxx_messageInfo_ReadReportReply.DiscardUnknown(m)
}

var xxx_messageInfo_ReadReportReply proto.InternalMessageInfo

func (m *ReadReportReply) GetReport() *Report {
	if m != nil {
		return m.Report
	}
	return nil
}

// The request message for the delete request
type DeleteReportRequest struct {
	Id                   string   `protobuf:"bytes,1,opt,name=Id,proto3" json:"Id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeleteReportRequest) Reset()         { *m = DeleteReportRequest{} }
func (m *DeleteReportRequest) String() string { return proto.CompactTextString(m) }
func (*DeleteReportRequest) ProtoMessage()    {}
func (*DeleteReportRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_b0d9a2e7955692ed, []int{4}
}

func (m *DeleteReportRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeleteReportRequest.Unmarshal(m, b)
}
func (m *DeleteReportRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeleteReportRequest.Marshal(b, m, deterministic)
}
func (m *DeleteReportRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeleteReportRequest.Merge(m, src)
}
func (m *DeleteReportRequest) XXX_Size() int {
	return xxx_messageInfo_DeleteReportRequest.Size(m)
}
func (m *DeleteReportRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_DeleteReportRequest.DiscardUnknown(m)
}

var xxx_messageInfo_DeleteReportRequest proto.InternalMessageInfo

func (m *DeleteReportRequest) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

// The response message to the delete request
type DeleteReportReply struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeleteReportReply) Reset()         { *m = DeleteReportReply{} }
func (m *DeleteReportReply) String() string { return proto.CompactTextString(m) }
func (*DeleteReportReply) ProtoMessage()    {}
func (*DeleteReportReply) Descriptor() ([]byte, []int) {
	return fileDescriptor_b0d9a2e7955692ed, []int{5}
}

func (m *DeleteReportReply) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeleteReportReply.Unmarshal(m, b)
}
func (m *DeleteReportReply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeleteReportReply.Marshal(b, m, deterministic)
}
func (m *DeleteReportReply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeleteReportReply.Merge(m, src)
}
func (m *DeleteReportReply) XXX_Size() int {
	return xxx_messageInfo_DeleteReportReply.Size(m)
}
func (m *DeleteReportReply) XXX_DiscardUnknown() {
	xxx_messageInfo_DeleteReportReply.DiscardUnknown(m)
}

var xxx_messageInfo_DeleteReportReply proto.InternalMessageInfo

// The request message for the update request
type UpdateReportRequest struct {
	Id                   string   `protobuf:"bytes,1,opt,name=Id,proto3" json:"Id,omitempty"`
	Name                 string   `protobuf:"bytes,2,opt,name=Name,proto3" json:"Name,omitempty"`
	Code                 string   `protobuf:"bytes,3,opt,name=Code,proto3" json:"Code,omitempty"`
	Description          string   `protobuf:"bytes,4,opt,name=Description,proto3" json:"Description,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UpdateReportRequest) Reset()         { *m = UpdateReportRequest{} }
func (m *UpdateReportRequest) String() string { return proto.CompactTextString(m) }
func (*UpdateReportRequest) ProtoMessage()    {}
func (*UpdateReportRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_b0d9a2e7955692ed, []int{6}
}

func (m *UpdateReportRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdateReportRequest.Unmarshal(m, b)
}
func (m *UpdateReportRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdateReportRequest.Marshal(b, m, deterministic)
}
func (m *UpdateReportRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdateReportRequest.Merge(m, src)
}
func (m *UpdateReportRequest) XXX_Size() int {
	return xxx_messageInfo_UpdateReportRequest.Size(m)
}
func (m *UpdateReportRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdateReportRequest.DiscardUnknown(m)
}

var xxx_messageInfo_UpdateReportRequest proto.InternalMessageInfo

func (m *UpdateReportRequest) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *UpdateReportRequest) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *UpdateReportRequest) GetCode() string {
	if m != nil {
		return m.Code
	}
	return ""
}

func (m *UpdateReportRequest) GetDescription() string {
	if m != nil {
		return m.Description
	}
	return ""
}

// The response message to the update request.
// Returns the old values for the Report
type UpdateReportReply struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UpdateReportReply) Reset()         { *m = UpdateReportReply{} }
func (m *UpdateReportReply) String() string { return proto.CompactTextString(m) }
func (*UpdateReportReply) ProtoMessage()    {}
func (*UpdateReportReply) Descriptor() ([]byte, []int) {
	return fileDescriptor_b0d9a2e7955692ed, []int{7}
}

func (m *UpdateReportReply) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdateReportReply.Unmarshal(m, b)
}
func (m *UpdateReportReply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdateReportReply.Marshal(b, m, deterministic)
}
func (m *UpdateReportReply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdateReportReply.Merge(m, src)
}
func (m *UpdateReportReply) XXX_Size() int {
	return xxx_messageInfo_UpdateReportReply.Size(m)
}
func (m *UpdateReportReply) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdateReportReply.DiscardUnknown(m)
}

var xxx_messageInfo_UpdateReportReply proto.InternalMessageInfo

// The request message for the list reports request
type ListReportsRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ListReportsRequest) Reset()         { *m = ListReportsRequest{} }
func (m *ListReportsRequest) String() string { return proto.CompactTextString(m) }
func (*ListReportsRequest) ProtoMessage()    {}
func (*ListReportsRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_b0d9a2e7955692ed, []int{8}
}

func (m *ListReportsRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListReportsRequest.Unmarshal(m, b)
}
func (m *ListReportsRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListReportsRequest.Marshal(b, m, deterministic)
}
func (m *ListReportsRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListReportsRequest.Merge(m, src)
}
func (m *ListReportsRequest) XXX_Size() int {
	return xxx_messageInfo_ListReportsRequest.Size(m)
}
func (m *ListReportsRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ListReportsRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ListReportsRequest proto.InternalMessageInfo

// The response message to the list reports request.
type ListReportsReply struct {
	Reports              []*Report `protobuf:"bytes,1,rep,name=reports,proto3" json:"reports,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *ListReportsReply) Reset()         { *m = ListReportsReply{} }
func (m *ListReportsReply) String() string { return proto.CompactTextString(m) }
func (*ListReportsReply) ProtoMessage()    {}
func (*ListReportsReply) Descriptor() ([]byte, []int) {
	return fileDescriptor_b0d9a2e7955692ed, []int{9}
}

func (m *ListReportsReply) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListReportsReply.Unmarshal(m, b)
}
func (m *ListReportsReply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListReportsReply.Marshal(b, m, deterministic)
}
func (m *ListReportsReply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListReportsReply.Merge(m, src)
}
func (m *ListReportsReply) XXX_Size() int {
	return xxx_messageInfo_ListReportsReply.Size(m)
}
func (m *ListReportsReply) XXX_DiscardUnknown() {
	xxx_messageInfo_ListReportsReply.DiscardUnknown(m)
}

var xxx_messageInfo_ListReportsReply proto.InternalMessageInfo

func (m *ListReportsReply) GetReports() []*Report {
	if m != nil {
		return m.Reports
	}
	return nil
}

type Report struct {
	Id                   string                   `protobuf:"bytes,1,opt,name=Id,proto3" json:"Id,omitempty"`
	Name                 string                   `protobuf:"bytes,2,opt,name=Name,proto3" json:"Name,omitempty"`
	OrderId              string                   `protobuf:"bytes,3,opt,name=OrderId,proto3" json:"OrderId,omitempty"`
	Period               *Interval                `protobuf:"bytes,4,opt,name=Period,proto3" json:"Period,omitempty"`
	Activities           []*activitycomm.Activity `protobuf:"bytes,5,rep,name=Activities,proto3" json:"Activities,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                 `json:"-"`
	XXX_unrecognized     []byte                   `json:"-"`
	XXX_sizecache        int32                    `json:"-"`
}

func (m *Report) Reset()         { *m = Report{} }
func (m *Report) String() string { return proto.CompactTextString(m) }
func (*Report) ProtoMessage()    {}
func (*Report) Descriptor() ([]byte, []int) {
	return fileDescriptor_b0d9a2e7955692ed, []int{10}
}

func (m *Report) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Report.Unmarshal(m, b)
}
func (m *Report) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Report.Marshal(b, m, deterministic)
}
func (m *Report) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Report.Merge(m, src)
}
func (m *Report) XXX_Size() int {
	return xxx_messageInfo_Report.Size(m)
}
func (m *Report) XXX_DiscardUnknown() {
	xxx_messageInfo_Report.DiscardUnknown(m)
}

var xxx_messageInfo_Report proto.InternalMessageInfo

func (m *Report) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *Report) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Report) GetOrderId() string {
	if m != nil {
		return m.OrderId
	}
	return ""
}

func (m *Report) GetPeriod() *Interval {
	if m != nil {
		return m.Period
	}
	return nil
}

func (m *Report) GetActivities() []*activitycomm.Activity {
	if m != nil {
		return m.Activities
	}
	return nil
}

type Interval struct {
	From                 *timestamp.Timestamp `protobuf:"bytes,1,opt,name=from,proto3" json:"from,omitempty"`
	To                   *timestamp.Timestamp `protobuf:"bytes,2,opt,name=to,proto3" json:"to,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *Interval) Reset()         { *m = Interval{} }
func (m *Interval) String() string { return proto.CompactTextString(m) }
func (*Interval) ProtoMessage()    {}
func (*Interval) Descriptor() ([]byte, []int) {
	return fileDescriptor_b0d9a2e7955692ed, []int{11}
}

func (m *Interval) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Interval.Unmarshal(m, b)
}
func (m *Interval) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Interval.Marshal(b, m, deterministic)
}
func (m *Interval) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Interval.Merge(m, src)
}
func (m *Interval) XXX_Size() int {
	return xxx_messageInfo_Interval.Size(m)
}
func (m *Interval) XXX_DiscardUnknown() {
	xxx_messageInfo_Interval.DiscardUnknown(m)
}

var xxx_messageInfo_Interval proto.InternalMessageInfo

func (m *Interval) GetFrom() *timestamp.Timestamp {
	if m != nil {
		return m.From
	}
	return nil
}

func (m *Interval) GetTo() *timestamp.Timestamp {
	if m != nil {
		return m.To
	}
	return nil
}

func init() {
	proto.RegisterType((*CreateReportRequest)(nil), "reportcomm.CreateReportRequest")
	proto.RegisterType((*CreateReportReply)(nil), "reportcomm.CreateReportReply")
	proto.RegisterType((*ReadReportRequest)(nil), "reportcomm.ReadReportRequest")
	proto.RegisterType((*ReadReportReply)(nil), "reportcomm.ReadReportReply")
	proto.RegisterType((*DeleteReportRequest)(nil), "reportcomm.DeleteReportRequest")
	proto.RegisterType((*DeleteReportReply)(nil), "reportcomm.DeleteReportReply")
	proto.RegisterType((*UpdateReportRequest)(nil), "reportcomm.UpdateReportRequest")
	proto.RegisterType((*UpdateReportReply)(nil), "reportcomm.UpdateReportReply")
	proto.RegisterType((*ListReportsRequest)(nil), "reportcomm.ListReportsRequest")
	proto.RegisterType((*ListReportsReply)(nil), "reportcomm.ListReportsReply")
	proto.RegisterType((*Report)(nil), "reportcomm.Report")
	proto.RegisterType((*Interval)(nil), "reportcomm.Interval")
}

func init() {
	proto.RegisterFile("reportcomm/report.proto", fileDescriptor_b0d9a2e7955692ed)
}

var fileDescriptor_b0d9a2e7955692ed = []byte{
	// 493 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x8c, 0x54, 0x51, 0x6b, 0xd4, 0x40,
	0x10, 0x6e, 0x72, 0x31, 0xb5, 0x73, 0x50, 0xed, 0x5c, 0xd1, 0x90, 0x5a, 0x7b, 0x44, 0x84, 0x52,
	0xca, 0x1e, 0x9c, 0xe0, 0x9b, 0xa0, 0xf6, 0x10, 0xaf, 0x88, 0x4a, 0x54, 0x04, 0xdf, 0xd2, 0xcb,
	0x5c, 0x09, 0x24, 0xdd, 0xb8, 0xd9, 0x1e, 0xdc, 0x7f, 0xf2, 0xc5, 0x7f, 0x28, 0xd9, 0xdd, 0xd8,
	0xdd, 0x6b, 0xcf, 0xf3, 0x6d, 0x77, 0xe6, 0xcb, 0x37, 0xdf, 0xcc, 0x7e, 0x13, 0x78, 0x2c, 0xa8,
	0xe6, 0x42, 0xce, 0x78, 0x55, 0x8d, 0xf4, 0x91, 0xd5, 0x82, 0x4b, 0x8e, 0x70, 0x93, 0x88, 0x8f,
	0x2e, 0x39, 0xbf, 0x2c, 0x69, 0xa4, 0x32, 0x17, 0xd7, 0xf3, 0x91, 0x2c, 0x2a, 0x6a, 0x64, 0x56,
	0xd5, 0x1a, 0x1c, 0x1f, 0x64, 0x33, 0x59, 0x2c, 0x0a, 0xb9, 0x54, 0x3c, 0xdd, 0x45, 0x27, 0x93,
	0xef, 0x30, 0x38, 0x13, 0x94, 0x49, 0x4a, 0x15, 0x63, 0x4a, 0x3f, 0xaf, 0xa9, 0x91, 0x88, 0x10,
	0x7c, 0xcc, 0x2a, 0x8a, 0xbc, 0xa1, 0x77, 0xbc, 0x93, 0xaa, 0x33, 0x9e, 0x42, 0xf8, 0x99, 0x44,
	0xc1, 0xf3, 0xc8, 0x1f, 0x7a, 0xc7, 0xfd, 0xf1, 0x3e, 0xbb, 0x51, 0xc1, 0xa6, 0x57, 0x92, 0xc4,
	0x22, 0x2b, 0x53, 0x83, 0x49, 0x9e, 0xc1, 0x9e, 0x4b, 0x5c, 0x97, 0x4b, 0xdc, 0x05, 0x7f, 0x9a,
	0x1b, 0x52, 0x7f, 0xaa, 0x40, 0x29, 0x65, 0xb9, 0x5b, 0x7b, 0x15, 0xf4, 0x0a, 0x1e, 0xd8, 0xa0,
	0x96, 0xe7, 0x04, 0x42, 0x5d, 0x5b, 0xc1, 0xfa, 0x63, 0xb4, 0xa5, 0x18, 0xa0, 0x41, 0x24, 0xcf,
	0x61, 0x30, 0xa1, 0x92, 0x56, 0x3b, 0x5c, 0xad, 0x32, 0x80, 0x3d, 0x17, 0x56, 0x97, 0xcb, 0x84,
	0xc3, 0xe0, 0x5b, 0x9d, 0x67, 0x1b, 0xbe, 0xfd, 0x3b, 0x2d, 0xdf, 0x9a, 0x16, 0x42, 0x70, 0xc6,
	0x73, 0x8a, 0x7a, 0x3a, 0xd6, 0x9e, 0x71, 0x08, 0xfd, 0x09, 0x35, 0x33, 0x51, 0xd4, 0xb2, 0xe0,
	0x57, 0x51, 0xa0, 0x52, 0x76, 0xa8, 0x55, 0xe1, 0x16, 0x6c, 0x55, 0xec, 0x03, 0x7e, 0x28, 0x1a,
	0xa9, 0x43, 0x8d, 0x11, 0x91, 0xbc, 0x86, 0x87, 0x4e, 0xb4, 0x9d, 0xcb, 0x29, 0x6c, 0xeb, 0xae,
	0x9b, 0xc8, 0x1b, 0xf6, 0xd6, 0x0c, 0xa6, 0x83, 0x24, 0xbf, 0x3c, 0x08, 0x75, 0xec, 0xbf, 0x3a,
	0x8a, 0x60, 0xfb, 0x93, 0xc8, 0x49, 0x4c, 0x73, 0xd3, 0x54, 0x77, 0xb5, 0x9c, 0x11, 0x6c, 0x76,
	0x06, 0xbe, 0x04, 0x78, 0xa3, 0x4d, 0x58, 0x50, 0x13, 0xdd, 0x53, 0x3a, 0x1f, 0x31, 0xdb, 0xa4,
	0xcc, 0xe4, 0x97, 0xa9, 0x85, 0x4c, 0xe6, 0x70, 0xbf, 0xe3, 0x42, 0x06, 0xc1, 0x5c, 0xf0, 0xca,
	0x3c, 0x7f, 0xcc, 0xf4, 0x0e, 0xb0, 0x6e, 0x07, 0xd8, 0xd7, 0x6e, 0x07, 0x52, 0x85, 0xc3, 0x13,
	0xf0, 0x25, 0x37, 0xbe, 0xfd, 0x17, 0xda, 0x97, 0x7c, 0xfc, 0xdb, 0x87, 0x1d, 0x3d, 0x96, 0x2f,
	0x8b, 0x19, 0x9e, 0x43, 0xa8, 0x7d, 0x8c, 0x47, 0x76, 0x57, 0x77, 0x2c, 0x4d, 0x7c, 0xb8, 0x1e,
	0xd0, 0x3e, 0xe3, 0x16, 0x4e, 0x20, 0x68, 0x9d, 0x8c, 0x87, 0xee, 0xab, 0xac, 0x2c, 0x40, 0x7c,
	0xb0, 0x2e, 0xad, 0x59, 0xce, 0x21, 0xd4, 0x4e, 0x75, 0x15, 0xdd, 0x61, 0x72, 0x57, 0xd1, 0x6d,
	0x7b, 0x6f, 0xe1, 0x3b, 0x08, 0x5a, 0x13, 0xe1, 0x53, 0x1b, 0x78, 0xdb, 0x6c, 0xf1, 0x93, 0xb5,
	0x79, 0xc5, 0xf3, 0x76, 0xf7, 0x7d, 0xef, 0x87, 0xf5, 0x53, 0xba, 0x08, 0xd5, 0x6c, 0x5f, 0xfc,
	0x09, 0x00, 0x00, 0xff, 0xff, 0xb7, 0x43, 0x67, 0x4f, 0xc2, 0x04, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConnInterface

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion6

// ReportSvcClient is the client API for ReportSvc service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type ReportSvcClient interface {
	// Creates a new report
	Create(ctx context.Context, in *CreateReportRequest, opts ...grpc.CallOption) (*CreateReportReply, error)
	// Reads an report
	Read(ctx context.Context, in *ReadReportRequest, opts ...grpc.CallOption) (*ReadReportReply, error)
	// Delete an report
	Delete(ctx context.Context, in *DeleteReportRequest, opts ...grpc.CallOption) (*DeleteReportReply, error)
	// List an report
	List(ctx context.Context, in *ListReportsRequest, opts ...grpc.CallOption) (*ListReportsReply, error)
}

type reportSvcClient struct {
	cc grpc.ClientConnInterface
}

func NewReportSvcClient(cc grpc.ClientConnInterface) ReportSvcClient {
	return &reportSvcClient{cc}
}

func (c *reportSvcClient) Create(ctx context.Context, in *CreateReportRequest, opts ...grpc.CallOption) (*CreateReportReply, error) {
	out := new(CreateReportReply)
	err := c.cc.Invoke(ctx, "/reportcomm.ReportSvc/Create", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *reportSvcClient) Read(ctx context.Context, in *ReadReportRequest, opts ...grpc.CallOption) (*ReadReportReply, error) {
	out := new(ReadReportReply)
	err := c.cc.Invoke(ctx, "/reportcomm.ReportSvc/Read", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *reportSvcClient) Delete(ctx context.Context, in *DeleteReportRequest, opts ...grpc.CallOption) (*DeleteReportReply, error) {
	out := new(DeleteReportReply)
	err := c.cc.Invoke(ctx, "/reportcomm.ReportSvc/Delete", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *reportSvcClient) List(ctx context.Context, in *ListReportsRequest, opts ...grpc.CallOption) (*ListReportsReply, error) {
	out := new(ListReportsReply)
	err := c.cc.Invoke(ctx, "/reportcomm.ReportSvc/List", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ReportSvcServer is the server API for ReportSvc service.
type ReportSvcServer interface {
	// Creates a new report
	Create(context.Context, *CreateReportRequest) (*CreateReportReply, error)
	// Reads an report
	Read(context.Context, *ReadReportRequest) (*ReadReportReply, error)
	// Delete an report
	Delete(context.Context, *DeleteReportRequest) (*DeleteReportReply, error)
	// List an report
	List(context.Context, *ListReportsRequest) (*ListReportsReply, error)
}

// UnimplementedReportSvcServer can be embedded to have forward compatible implementations.
type UnimplementedReportSvcServer struct {
}

func (*UnimplementedReportSvcServer) Create(ctx context.Context, req *CreateReportRequest) (*CreateReportReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Create not implemented")
}
func (*UnimplementedReportSvcServer) Read(ctx context.Context, req *ReadReportRequest) (*ReadReportReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Read not implemented")
}
func (*UnimplementedReportSvcServer) Delete(ctx context.Context, req *DeleteReportRequest) (*DeleteReportReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Delete not implemented")
}
func (*UnimplementedReportSvcServer) List(ctx context.Context, req *ListReportsRequest) (*ListReportsReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method List not implemented")
}

func RegisterReportSvcServer(s *grpc.Server, srv ReportSvcServer) {
	s.RegisterService(&_ReportSvc_serviceDesc, srv)
}

func _ReportSvc_Create_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateReportRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ReportSvcServer).Create(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/reportcomm.ReportSvc/Create",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ReportSvcServer).Create(ctx, req.(*CreateReportRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ReportSvc_Read_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ReadReportRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ReportSvcServer).Read(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/reportcomm.ReportSvc/Read",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ReportSvcServer).Read(ctx, req.(*ReadReportRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ReportSvc_Delete_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteReportRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ReportSvcServer).Delete(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/reportcomm.ReportSvc/Delete",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ReportSvcServer).Delete(ctx, req.(*DeleteReportRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ReportSvc_List_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListReportsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ReportSvcServer).List(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/reportcomm.ReportSvc/List",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ReportSvcServer).List(ctx, req.(*ListReportsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _ReportSvc_serviceDesc = grpc.ServiceDesc{
	ServiceName: "reportcomm.ReportSvc",
	HandlerType: (*ReportSvcServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Create",
			Handler:    _ReportSvc_Create_Handler,
		},
		{
			MethodName: "Read",
			Handler:    _ReportSvc_Read_Handler,
		},
		{
			MethodName: "Delete",
			Handler:    _ReportSvc_Delete_Handler,
		},
		{
			MethodName: "List",
			Handler:    _ReportSvc_List_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "reportcomm/report.proto",
}
