// Code generated by protoc-gen-go. DO NOT EDIT.
// source: activity.proto

package comm

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// The request message containing the activity details
type CreateActivityRequest struct {
	Name                 string   `protobuf:"bytes,1,opt,name=Name,proto3" json:"Name,omitempty"`
	Code                 string   `protobuf:"bytes,2,opt,name=Code,proto3" json:"Code,omitempty"`
	Description          string   `protobuf:"bytes,3,opt,name=Description,proto3" json:"Description,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateActivityRequest) Reset()         { *m = CreateActivityRequest{} }
func (m *CreateActivityRequest) String() string { return proto.CompactTextString(m) }
func (*CreateActivityRequest) ProtoMessage()    {}
func (*CreateActivityRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_a684c9a0549e7832, []int{0}
}

func (m *CreateActivityRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateActivityRequest.Unmarshal(m, b)
}
func (m *CreateActivityRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateActivityRequest.Marshal(b, m, deterministic)
}
func (m *CreateActivityRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateActivityRequest.Merge(m, src)
}
func (m *CreateActivityRequest) XXX_Size() int {
	return xxx_messageInfo_CreateActivityRequest.Size(m)
}
func (m *CreateActivityRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateActivityRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CreateActivityRequest proto.InternalMessageInfo

func (m *CreateActivityRequest) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *CreateActivityRequest) GetCode() string {
	if m != nil {
		return m.Code
	}
	return ""
}

func (m *CreateActivityRequest) GetDescription() string {
	if m != nil {
		return m.Description
	}
	return ""
}

// The response message containing the id of the activity
type CreateActivityReply struct {
	Id                   string   `protobuf:"bytes,1,opt,name=Id,proto3" json:"Id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateActivityReply) Reset()         { *m = CreateActivityReply{} }
func (m *CreateActivityReply) String() string { return proto.CompactTextString(m) }
func (*CreateActivityReply) ProtoMessage()    {}
func (*CreateActivityReply) Descriptor() ([]byte, []int) {
	return fileDescriptor_a684c9a0549e7832, []int{1}
}

func (m *CreateActivityReply) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateActivityReply.Unmarshal(m, b)
}
func (m *CreateActivityReply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateActivityReply.Marshal(b, m, deterministic)
}
func (m *CreateActivityReply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateActivityReply.Merge(m, src)
}
func (m *CreateActivityReply) XXX_Size() int {
	return xxx_messageInfo_CreateActivityReply.Size(m)
}
func (m *CreateActivityReply) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateActivityReply.DiscardUnknown(m)
}

var xxx_messageInfo_CreateActivityReply proto.InternalMessageInfo

func (m *CreateActivityReply) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

// The request message for the read request
type ReadActivityRequest struct {
	Id                   string   `protobuf:"bytes,1,opt,name=Id,proto3" json:"Id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ReadActivityRequest) Reset()         { *m = ReadActivityRequest{} }
func (m *ReadActivityRequest) String() string { return proto.CompactTextString(m) }
func (*ReadActivityRequest) ProtoMessage()    {}
func (*ReadActivityRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_a684c9a0549e7832, []int{2}
}

func (m *ReadActivityRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ReadActivityRequest.Unmarshal(m, b)
}
func (m *ReadActivityRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ReadActivityRequest.Marshal(b, m, deterministic)
}
func (m *ReadActivityRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ReadActivityRequest.Merge(m, src)
}
func (m *ReadActivityRequest) XXX_Size() int {
	return xxx_messageInfo_ReadActivityRequest.Size(m)
}
func (m *ReadActivityRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ReadActivityRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ReadActivityRequest proto.InternalMessageInfo

func (m *ReadActivityRequest) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

// The response message to the read request
type ReadActivityReply struct {
	Activity             *Activity `protobuf:"bytes,1,opt,name=activity,proto3" json:"activity,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *ReadActivityReply) Reset()         { *m = ReadActivityReply{} }
func (m *ReadActivityReply) String() string { return proto.CompactTextString(m) }
func (*ReadActivityReply) ProtoMessage()    {}
func (*ReadActivityReply) Descriptor() ([]byte, []int) {
	return fileDescriptor_a684c9a0549e7832, []int{3}
}

func (m *ReadActivityReply) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ReadActivityReply.Unmarshal(m, b)
}
func (m *ReadActivityReply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ReadActivityReply.Marshal(b, m, deterministic)
}
func (m *ReadActivityReply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ReadActivityReply.Merge(m, src)
}
func (m *ReadActivityReply) XXX_Size() int {
	return xxx_messageInfo_ReadActivityReply.Size(m)
}
func (m *ReadActivityReply) XXX_DiscardUnknown() {
	xxx_messageInfo_ReadActivityReply.DiscardUnknown(m)
}

var xxx_messageInfo_ReadActivityReply proto.InternalMessageInfo

func (m *ReadActivityReply) GetActivity() *Activity {
	if m != nil {
		return m.Activity
	}
	return nil
}

// The request message for the delete request
type DeleteActivityRequest struct {
	Id                   string   `protobuf:"bytes,1,opt,name=Id,proto3" json:"Id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeleteActivityRequest) Reset()         { *m = DeleteActivityRequest{} }
func (m *DeleteActivityRequest) String() string { return proto.CompactTextString(m) }
func (*DeleteActivityRequest) ProtoMessage()    {}
func (*DeleteActivityRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_a684c9a0549e7832, []int{4}
}

func (m *DeleteActivityRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeleteActivityRequest.Unmarshal(m, b)
}
func (m *DeleteActivityRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeleteActivityRequest.Marshal(b, m, deterministic)
}
func (m *DeleteActivityRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeleteActivityRequest.Merge(m, src)
}
func (m *DeleteActivityRequest) XXX_Size() int {
	return xxx_messageInfo_DeleteActivityRequest.Size(m)
}
func (m *DeleteActivityRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_DeleteActivityRequest.DiscardUnknown(m)
}

var xxx_messageInfo_DeleteActivityRequest proto.InternalMessageInfo

func (m *DeleteActivityRequest) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

// The response message to the delete request
type DeleteActivityReply struct {
	Activity             *Activity `protobuf:"bytes,1,opt,name=activity,proto3" json:"activity,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *DeleteActivityReply) Reset()         { *m = DeleteActivityReply{} }
func (m *DeleteActivityReply) String() string { return proto.CompactTextString(m) }
func (*DeleteActivityReply) ProtoMessage()    {}
func (*DeleteActivityReply) Descriptor() ([]byte, []int) {
	return fileDescriptor_a684c9a0549e7832, []int{5}
}

func (m *DeleteActivityReply) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeleteActivityReply.Unmarshal(m, b)
}
func (m *DeleteActivityReply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeleteActivityReply.Marshal(b, m, deterministic)
}
func (m *DeleteActivityReply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeleteActivityReply.Merge(m, src)
}
func (m *DeleteActivityReply) XXX_Size() int {
	return xxx_messageInfo_DeleteActivityReply.Size(m)
}
func (m *DeleteActivityReply) XXX_DiscardUnknown() {
	xxx_messageInfo_DeleteActivityReply.DiscardUnknown(m)
}

var xxx_messageInfo_DeleteActivityReply proto.InternalMessageInfo

func (m *DeleteActivityReply) GetActivity() *Activity {
	if m != nil {
		return m.Activity
	}
	return nil
}

// The request message for the update request
type UpdateActivityRequest struct {
	Id                   string   `protobuf:"bytes,1,opt,name=Id,proto3" json:"Id,omitempty"`
	Name                 string   `protobuf:"bytes,2,opt,name=Name,proto3" json:"Name,omitempty"`
	Code                 string   `protobuf:"bytes,3,opt,name=Code,proto3" json:"Code,omitempty"`
	Description          string   `protobuf:"bytes,4,opt,name=Description,proto3" json:"Description,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UpdateActivityRequest) Reset()         { *m = UpdateActivityRequest{} }
func (m *UpdateActivityRequest) String() string { return proto.CompactTextString(m) }
func (*UpdateActivityRequest) ProtoMessage()    {}
func (*UpdateActivityRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_a684c9a0549e7832, []int{6}
}

func (m *UpdateActivityRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdateActivityRequest.Unmarshal(m, b)
}
func (m *UpdateActivityRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdateActivityRequest.Marshal(b, m, deterministic)
}
func (m *UpdateActivityRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdateActivityRequest.Merge(m, src)
}
func (m *UpdateActivityRequest) XXX_Size() int {
	return xxx_messageInfo_UpdateActivityRequest.Size(m)
}
func (m *UpdateActivityRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdateActivityRequest.DiscardUnknown(m)
}

var xxx_messageInfo_UpdateActivityRequest proto.InternalMessageInfo

func (m *UpdateActivityRequest) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *UpdateActivityRequest) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *UpdateActivityRequest) GetCode() string {
	if m != nil {
		return m.Code
	}
	return ""
}

func (m *UpdateActivityRequest) GetDescription() string {
	if m != nil {
		return m.Description
	}
	return ""
}

// The response message to the update request.
// Returns the old values for the Activity
type UpdateActivityReply struct {
	Activity             *Activity `protobuf:"bytes,1,opt,name=activity,proto3" json:"activity,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *UpdateActivityReply) Reset()         { *m = UpdateActivityReply{} }
func (m *UpdateActivityReply) String() string { return proto.CompactTextString(m) }
func (*UpdateActivityReply) ProtoMessage()    {}
func (*UpdateActivityReply) Descriptor() ([]byte, []int) {
	return fileDescriptor_a684c9a0549e7832, []int{7}
}

func (m *UpdateActivityReply) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdateActivityReply.Unmarshal(m, b)
}
func (m *UpdateActivityReply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdateActivityReply.Marshal(b, m, deterministic)
}
func (m *UpdateActivityReply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdateActivityReply.Merge(m, src)
}
func (m *UpdateActivityReply) XXX_Size() int {
	return xxx_messageInfo_UpdateActivityReply.Size(m)
}
func (m *UpdateActivityReply) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdateActivityReply.DiscardUnknown(m)
}

var xxx_messageInfo_UpdateActivityReply proto.InternalMessageInfo

func (m *UpdateActivityReply) GetActivity() *Activity {
	if m != nil {
		return m.Activity
	}
	return nil
}

// The request message for the list activities request
type ListActivitiesRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ListActivitiesRequest) Reset()         { *m = ListActivitiesRequest{} }
func (m *ListActivitiesRequest) String() string { return proto.CompactTextString(m) }
func (*ListActivitiesRequest) ProtoMessage()    {}
func (*ListActivitiesRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_a684c9a0549e7832, []int{8}
}

func (m *ListActivitiesRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListActivitiesRequest.Unmarshal(m, b)
}
func (m *ListActivitiesRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListActivitiesRequest.Marshal(b, m, deterministic)
}
func (m *ListActivitiesRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListActivitiesRequest.Merge(m, src)
}
func (m *ListActivitiesRequest) XXX_Size() int {
	return xxx_messageInfo_ListActivitiesRequest.Size(m)
}
func (m *ListActivitiesRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ListActivitiesRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ListActivitiesRequest proto.InternalMessageInfo

// The response message to the list activities request.
type ListActivitiesReply struct {
	Activities           []*Activity `protobuf:"bytes,1,rep,name=activities,proto3" json:"activities,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *ListActivitiesReply) Reset()         { *m = ListActivitiesReply{} }
func (m *ListActivitiesReply) String() string { return proto.CompactTextString(m) }
func (*ListActivitiesReply) ProtoMessage()    {}
func (*ListActivitiesReply) Descriptor() ([]byte, []int) {
	return fileDescriptor_a684c9a0549e7832, []int{9}
}

func (m *ListActivitiesReply) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListActivitiesReply.Unmarshal(m, b)
}
func (m *ListActivitiesReply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListActivitiesReply.Marshal(b, m, deterministic)
}
func (m *ListActivitiesReply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListActivitiesReply.Merge(m, src)
}
func (m *ListActivitiesReply) XXX_Size() int {
	return xxx_messageInfo_ListActivitiesReply.Size(m)
}
func (m *ListActivitiesReply) XXX_DiscardUnknown() {
	xxx_messageInfo_ListActivitiesReply.DiscardUnknown(m)
}

var xxx_messageInfo_ListActivitiesReply proto.InternalMessageInfo

func (m *ListActivitiesReply) GetActivities() []*Activity {
	if m != nil {
		return m.Activities
	}
	return nil
}

type Activity struct {
	Id                   string   `protobuf:"bytes,1,opt,name=Id,proto3" json:"Id,omitempty"`
	Name                 string   `protobuf:"bytes,2,opt,name=Name,proto3" json:"Name,omitempty"`
	Code                 string   `protobuf:"bytes,3,opt,name=Code,proto3" json:"Code,omitempty"`
	Description          string   `protobuf:"bytes,4,opt,name=Description,proto3" json:"Description,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Activity) Reset()         { *m = Activity{} }
func (m *Activity) String() string { return proto.CompactTextString(m) }
func (*Activity) ProtoMessage()    {}
func (*Activity) Descriptor() ([]byte, []int) {
	return fileDescriptor_a684c9a0549e7832, []int{10}
}

func (m *Activity) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Activity.Unmarshal(m, b)
}
func (m *Activity) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Activity.Marshal(b, m, deterministic)
}
func (m *Activity) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Activity.Merge(m, src)
}
func (m *Activity) XXX_Size() int {
	return xxx_messageInfo_Activity.Size(m)
}
func (m *Activity) XXX_DiscardUnknown() {
	xxx_messageInfo_Activity.DiscardUnknown(m)
}

var xxx_messageInfo_Activity proto.InternalMessageInfo

func (m *Activity) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *Activity) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Activity) GetCode() string {
	if m != nil {
		return m.Code
	}
	return ""
}

func (m *Activity) GetDescription() string {
	if m != nil {
		return m.Description
	}
	return ""
}

func init() {
	proto.RegisterType((*CreateActivityRequest)(nil), "comm.CreateActivityRequest")
	proto.RegisterType((*CreateActivityReply)(nil), "comm.CreateActivityReply")
	proto.RegisterType((*ReadActivityRequest)(nil), "comm.ReadActivityRequest")
	proto.RegisterType((*ReadActivityReply)(nil), "comm.ReadActivityReply")
	proto.RegisterType((*DeleteActivityRequest)(nil), "comm.DeleteActivityRequest")
	proto.RegisterType((*DeleteActivityReply)(nil), "comm.DeleteActivityReply")
	proto.RegisterType((*UpdateActivityRequest)(nil), "comm.UpdateActivityRequest")
	proto.RegisterType((*UpdateActivityReply)(nil), "comm.UpdateActivityReply")
	proto.RegisterType((*ListActivitiesRequest)(nil), "comm.ListActivitiesRequest")
	proto.RegisterType((*ListActivitiesReply)(nil), "comm.ListActivitiesReply")
	proto.RegisterType((*Activity)(nil), "comm.Activity")
}

func init() { proto.RegisterFile("activity.proto", fileDescriptor_a684c9a0549e7832) }

var fileDescriptor_a684c9a0549e7832 = []byte{
	// 364 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xb4, 0x54, 0x4f, 0x4b, 0xfb, 0x40,
	0x10, 0x6d, 0x37, 0xa1, 0xf4, 0x37, 0x85, 0xc2, 0x6f, 0x43, 0x68, 0xac, 0x97, 0xb2, 0x20, 0x8a,
	0x87, 0x1c, 0xea, 0x55, 0xd0, 0xfe, 0x11, 0x2c, 0x88, 0x87, 0x8a, 0x1f, 0x60, 0xcd, 0xee, 0x61,
	0xa1, 0x35, 0x69, 0xb3, 0x16, 0xfa, 0x51, 0xfd, 0x36, 0xb2, 0xd9, 0x6c, 0xa8, 0xdb, 0x11, 0xe9,
	0xc1, 0xdb, 0x32, 0xef, 0xe5, 0xcd, 0x9b, 0x99, 0x47, 0xa0, 0xcf, 0x33, 0xad, 0x76, 0x4a, 0xef,
	0xd3, 0x62, 0x9b, 0xeb, 0x9c, 0x86, 0x59, 0xbe, 0x5e, 0x33, 0x0e, 0xf1, 0x6c, 0x2b, 0xb9, 0x96,
	0x93, 0x1a, 0x5d, 0xca, 0xcd, 0x87, 0x2c, 0x35, 0xa5, 0x10, 0x3e, 0xf3, 0xb5, 0x4c, 0xda, 0xa3,
	0xf6, 0xd5, 0xbf, 0x65, 0xf5, 0x36, 0xb5, 0x59, 0x2e, 0x64, 0x42, 0x6c, 0xcd, 0xbc, 0xe9, 0x08,
	0x7a, 0x73, 0x59, 0x66, 0x5b, 0x55, 0x68, 0x95, 0xbf, 0x27, 0x41, 0x05, 0x1d, 0x96, 0xd8, 0x05,
	0x44, 0x7e, 0x8b, 0x62, 0xb5, 0xa7, 0x7d, 0x20, 0x0b, 0x51, 0xcb, 0x93, 0x85, 0x30, 0xb4, 0xa5,
	0xe4, 0xc2, 0xf7, 0xe1, 0xd3, 0xee, 0xe0, 0xff, 0x77, 0x9a, 0xd1, 0xba, 0x86, 0xae, 0x9b, 0xae,
	0xa2, 0xf6, 0xc6, 0xfd, 0xd4, 0x8c, 0x97, 0x36, 0xb4, 0x06, 0x67, 0x97, 0x10, 0xcf, 0xe5, 0x4a,
	0x1e, 0x4f, 0xec, 0x77, 0x9a, 0x40, 0xe4, 0x13, 0x4f, 0xed, 0xb5, 0x81, 0xf8, 0xb5, 0x10, 0xfc,
	0xd7, 0x5e, 0xcd, 0xb6, 0x09, 0xb2, 0xed, 0xe0, 0xe7, 0x6d, 0x87, 0xc7, 0xdb, 0x9e, 0x40, 0xe4,
	0xb7, 0x3c, 0xd5, 0xf5, 0x00, 0xe2, 0x27, 0x55, 0xea, 0x1a, 0x51, 0xb2, 0xac, 0x5d, 0xb3, 0x07,
	0x88, 0x7c, 0xc0, 0x68, 0xa7, 0x00, 0xbc, 0x29, 0x25, 0xed, 0x51, 0x80, 0xa8, 0x1f, 0x30, 0x98,
	0x80, 0xae, 0xab, 0xff, 0xdd, 0x22, 0xc6, 0x9f, 0x04, 0x7a, 0xae, 0xcd, 0xcb, 0x2e, 0xa3, 0x53,
	0xe8, 0xd8, 0x18, 0xd2, 0x73, 0xeb, 0x0d, 0xcd, 0xfd, 0xf0, 0x0c, 0x07, 0x8b, 0xd5, 0x9e, 0xb5,
	0xe8, 0x2d, 0x84, 0x26, 0x7c, 0xb4, 0x26, 0x21, 0x79, 0x1d, 0x0e, 0x30, 0xc8, 0x7e, 0x3d, 0x85,
	0x8e, 0x0d, 0x94, 0x73, 0x80, 0xe6, 0xd0, 0x39, 0x40, 0xb2, 0x67, 0x35, 0xec, 0x79, 0x9d, 0x06,
	0x9a, 0x2f, 0xa7, 0x81, 0x24, 0x81, 0xb5, 0xe8, 0x3d, 0x84, 0xe6, 0x8c, 0x4e, 0x01, 0xbd, 0xb5,
	0x53, 0x40, 0xee, 0xcd, 0x5a, 0x53, 0xf2, 0x18, 0xbc, 0x75, 0xaa, 0xdf, 0xc8, 0xcd, 0x57, 0x00,
	0x00, 0x00, 0xff, 0xff, 0x15, 0x66, 0x80, 0x16, 0x58, 0x04, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// ActivitySvcClient is the client API for ActivitySvc service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type ActivitySvcClient interface {
	// Creates a new activity
	Create(ctx context.Context, in *CreateActivityRequest, opts ...grpc.CallOption) (*CreateActivityReply, error)
	// Reads an activity
	Read(ctx context.Context, in *ReadActivityRequest, opts ...grpc.CallOption) (*ReadActivityReply, error)
	// Delete an activity
	Delete(ctx context.Context, in *DeleteActivityRequest, opts ...grpc.CallOption) (*DeleteActivityReply, error)
	// Update an activity
	Update(ctx context.Context, in *UpdateActivityRequest, opts ...grpc.CallOption) (*UpdateActivityReply, error)
	// List an activity
	List(ctx context.Context, in *ListActivitiesRequest, opts ...grpc.CallOption) (*ListActivitiesReply, error)
}

type activitySvcClient struct {
	cc *grpc.ClientConn
}

func NewActivitySvcClient(cc *grpc.ClientConn) ActivitySvcClient {
	return &activitySvcClient{cc}
}

func (c *activitySvcClient) Create(ctx context.Context, in *CreateActivityRequest, opts ...grpc.CallOption) (*CreateActivityReply, error) {
	out := new(CreateActivityReply)
	err := c.cc.Invoke(ctx, "/comm.ActivitySvc/Create", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *activitySvcClient) Read(ctx context.Context, in *ReadActivityRequest, opts ...grpc.CallOption) (*ReadActivityReply, error) {
	out := new(ReadActivityReply)
	err := c.cc.Invoke(ctx, "/comm.ActivitySvc/Read", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *activitySvcClient) Delete(ctx context.Context, in *DeleteActivityRequest, opts ...grpc.CallOption) (*DeleteActivityReply, error) {
	out := new(DeleteActivityReply)
	err := c.cc.Invoke(ctx, "/comm.ActivitySvc/Delete", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *activitySvcClient) Update(ctx context.Context, in *UpdateActivityRequest, opts ...grpc.CallOption) (*UpdateActivityReply, error) {
	out := new(UpdateActivityReply)
	err := c.cc.Invoke(ctx, "/comm.ActivitySvc/Update", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *activitySvcClient) List(ctx context.Context, in *ListActivitiesRequest, opts ...grpc.CallOption) (*ListActivitiesReply, error) {
	out := new(ListActivitiesReply)
	err := c.cc.Invoke(ctx, "/comm.ActivitySvc/List", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ActivitySvcServer is the server API for ActivitySvc service.
type ActivitySvcServer interface {
	// Creates a new activity
	Create(context.Context, *CreateActivityRequest) (*CreateActivityReply, error)
	// Reads an activity
	Read(context.Context, *ReadActivityRequest) (*ReadActivityReply, error)
	// Delete an activity
	Delete(context.Context, *DeleteActivityRequest) (*DeleteActivityReply, error)
	// Update an activity
	Update(context.Context, *UpdateActivityRequest) (*UpdateActivityReply, error)
	// List an activity
	List(context.Context, *ListActivitiesRequest) (*ListActivitiesReply, error)
}

// UnimplementedActivitySvcServer can be embedded to have forward compatible implementations.
type UnimplementedActivitySvcServer struct {
}

func (*UnimplementedActivitySvcServer) Create(ctx context.Context, req *CreateActivityRequest) (*CreateActivityReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Create not implemented")
}
func (*UnimplementedActivitySvcServer) Read(ctx context.Context, req *ReadActivityRequest) (*ReadActivityReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Read not implemented")
}
func (*UnimplementedActivitySvcServer) Delete(ctx context.Context, req *DeleteActivityRequest) (*DeleteActivityReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Delete not implemented")
}
func (*UnimplementedActivitySvcServer) Update(ctx context.Context, req *UpdateActivityRequest) (*UpdateActivityReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Update not implemented")
}
func (*UnimplementedActivitySvcServer) List(ctx context.Context, req *ListActivitiesRequest) (*ListActivitiesReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method List not implemented")
}

func RegisterActivitySvcServer(s *grpc.Server, srv ActivitySvcServer) {
	s.RegisterService(&_ActivitySvc_serviceDesc, srv)
}

func _ActivitySvc_Create_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateActivityRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ActivitySvcServer).Create(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/comm.ActivitySvc/Create",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ActivitySvcServer).Create(ctx, req.(*CreateActivityRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ActivitySvc_Read_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ReadActivityRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ActivitySvcServer).Read(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/comm.ActivitySvc/Read",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ActivitySvcServer).Read(ctx, req.(*ReadActivityRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ActivitySvc_Delete_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteActivityRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ActivitySvcServer).Delete(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/comm.ActivitySvc/Delete",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ActivitySvcServer).Delete(ctx, req.(*DeleteActivityRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ActivitySvc_Update_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateActivityRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ActivitySvcServer).Update(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/comm.ActivitySvc/Update",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ActivitySvcServer).Update(ctx, req.(*UpdateActivityRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ActivitySvc_List_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListActivitiesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ActivitySvcServer).List(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/comm.ActivitySvc/List",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ActivitySvcServer).List(ctx, req.(*ListActivitiesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _ActivitySvc_serviceDesc = grpc.ServiceDesc{
	ServiceName: "comm.ActivitySvc",
	HandlerType: (*ActivitySvcServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Create",
			Handler:    _ActivitySvc_Create_Handler,
		},
		{
			MethodName: "Read",
			Handler:    _ActivitySvc_Read_Handler,
		},
		{
			MethodName: "Delete",
			Handler:    _ActivitySvc_Delete_Handler,
		},
		{
			MethodName: "Update",
			Handler:    _ActivitySvc_Update_Handler,
		},
		{
			MethodName: "List",
			Handler:    _ActivitySvc_List_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "activity.proto",
}
