// Code generated by protoc-gen-go. DO NOT EDIT.
// source: ordercomm/order.proto

package ordercomm

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// The request message containing the order details
type CreateOrderRequest struct {
	Name                 string   `protobuf:"bytes,1,opt,name=Name,proto3" json:"Name,omitempty"`
	Code                 string   `protobuf:"bytes,2,opt,name=Code,proto3" json:"Code,omitempty"`
	Description          string   `protobuf:"bytes,3,opt,name=Description,proto3" json:"Description,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateOrderRequest) Reset()         { *m = CreateOrderRequest{} }
func (m *CreateOrderRequest) String() string { return proto.CompactTextString(m) }
func (*CreateOrderRequest) ProtoMessage()    {}
func (*CreateOrderRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_972d9d7dd8a32892, []int{0}
}

func (m *CreateOrderRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateOrderRequest.Unmarshal(m, b)
}
func (m *CreateOrderRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateOrderRequest.Marshal(b, m, deterministic)
}
func (m *CreateOrderRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateOrderRequest.Merge(m, src)
}
func (m *CreateOrderRequest) XXX_Size() int {
	return xxx_messageInfo_CreateOrderRequest.Size(m)
}
func (m *CreateOrderRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateOrderRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CreateOrderRequest proto.InternalMessageInfo

func (m *CreateOrderRequest) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *CreateOrderRequest) GetCode() string {
	if m != nil {
		return m.Code
	}
	return ""
}

func (m *CreateOrderRequest) GetDescription() string {
	if m != nil {
		return m.Description
	}
	return ""
}

// The response message containing the id of the order
type CreateOrderReply struct {
	Id                   string   `protobuf:"bytes,1,opt,name=Id,proto3" json:"Id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateOrderReply) Reset()         { *m = CreateOrderReply{} }
func (m *CreateOrderReply) String() string { return proto.CompactTextString(m) }
func (*CreateOrderReply) ProtoMessage()    {}
func (*CreateOrderReply) Descriptor() ([]byte, []int) {
	return fileDescriptor_972d9d7dd8a32892, []int{1}
}

func (m *CreateOrderReply) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateOrderReply.Unmarshal(m, b)
}
func (m *CreateOrderReply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateOrderReply.Marshal(b, m, deterministic)
}
func (m *CreateOrderReply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateOrderReply.Merge(m, src)
}
func (m *CreateOrderReply) XXX_Size() int {
	return xxx_messageInfo_CreateOrderReply.Size(m)
}
func (m *CreateOrderReply) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateOrderReply.DiscardUnknown(m)
}

var xxx_messageInfo_CreateOrderReply proto.InternalMessageInfo

func (m *CreateOrderReply) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

// The request message for the read request
type ReadOrderRequest struct {
	Id                   string   `protobuf:"bytes,1,opt,name=Id,proto3" json:"Id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ReadOrderRequest) Reset()         { *m = ReadOrderRequest{} }
func (m *ReadOrderRequest) String() string { return proto.CompactTextString(m) }
func (*ReadOrderRequest) ProtoMessage()    {}
func (*ReadOrderRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_972d9d7dd8a32892, []int{2}
}

func (m *ReadOrderRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ReadOrderRequest.Unmarshal(m, b)
}
func (m *ReadOrderRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ReadOrderRequest.Marshal(b, m, deterministic)
}
func (m *ReadOrderRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ReadOrderRequest.Merge(m, src)
}
func (m *ReadOrderRequest) XXX_Size() int {
	return xxx_messageInfo_ReadOrderRequest.Size(m)
}
func (m *ReadOrderRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ReadOrderRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ReadOrderRequest proto.InternalMessageInfo

func (m *ReadOrderRequest) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

// The response message to the read request
type ReadOrderReply struct {
	Order                *Order   `protobuf:"bytes,1,opt,name=order,proto3" json:"order,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ReadOrderReply) Reset()         { *m = ReadOrderReply{} }
func (m *ReadOrderReply) String() string { return proto.CompactTextString(m) }
func (*ReadOrderReply) ProtoMessage()    {}
func (*ReadOrderReply) Descriptor() ([]byte, []int) {
	return fileDescriptor_972d9d7dd8a32892, []int{3}
}

func (m *ReadOrderReply) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ReadOrderReply.Unmarshal(m, b)
}
func (m *ReadOrderReply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ReadOrderReply.Marshal(b, m, deterministic)
}
func (m *ReadOrderReply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ReadOrderReply.Merge(m, src)
}
func (m *ReadOrderReply) XXX_Size() int {
	return xxx_messageInfo_ReadOrderReply.Size(m)
}
func (m *ReadOrderReply) XXX_DiscardUnknown() {
	xxx_messageInfo_ReadOrderReply.DiscardUnknown(m)
}

var xxx_messageInfo_ReadOrderReply proto.InternalMessageInfo

func (m *ReadOrderReply) GetOrder() *Order {
	if m != nil {
		return m.Order
	}
	return nil
}

// The request message for the delete request
type DeleteOrderRequest struct {
	Id                   string   `protobuf:"bytes,1,opt,name=Id,proto3" json:"Id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeleteOrderRequest) Reset()         { *m = DeleteOrderRequest{} }
func (m *DeleteOrderRequest) String() string { return proto.CompactTextString(m) }
func (*DeleteOrderRequest) ProtoMessage()    {}
func (*DeleteOrderRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_972d9d7dd8a32892, []int{4}
}

func (m *DeleteOrderRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeleteOrderRequest.Unmarshal(m, b)
}
func (m *DeleteOrderRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeleteOrderRequest.Marshal(b, m, deterministic)
}
func (m *DeleteOrderRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeleteOrderRequest.Merge(m, src)
}
func (m *DeleteOrderRequest) XXX_Size() int {
	return xxx_messageInfo_DeleteOrderRequest.Size(m)
}
func (m *DeleteOrderRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_DeleteOrderRequest.DiscardUnknown(m)
}

var xxx_messageInfo_DeleteOrderRequest proto.InternalMessageInfo

func (m *DeleteOrderRequest) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

// The response message to the delete request
type DeleteOrderReply struct {
	Order                *Order   `protobuf:"bytes,1,opt,name=order,proto3" json:"order,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeleteOrderReply) Reset()         { *m = DeleteOrderReply{} }
func (m *DeleteOrderReply) String() string { return proto.CompactTextString(m) }
func (*DeleteOrderReply) ProtoMessage()    {}
func (*DeleteOrderReply) Descriptor() ([]byte, []int) {
	return fileDescriptor_972d9d7dd8a32892, []int{5}
}

func (m *DeleteOrderReply) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeleteOrderReply.Unmarshal(m, b)
}
func (m *DeleteOrderReply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeleteOrderReply.Marshal(b, m, deterministic)
}
func (m *DeleteOrderReply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeleteOrderReply.Merge(m, src)
}
func (m *DeleteOrderReply) XXX_Size() int {
	return xxx_messageInfo_DeleteOrderReply.Size(m)
}
func (m *DeleteOrderReply) XXX_DiscardUnknown() {
	xxx_messageInfo_DeleteOrderReply.DiscardUnknown(m)
}

var xxx_messageInfo_DeleteOrderReply proto.InternalMessageInfo

func (m *DeleteOrderReply) GetOrder() *Order {
	if m != nil {
		return m.Order
	}
	return nil
}

// The request message for the update request
type UpdateOrderRequest struct {
	Id                   string   `protobuf:"bytes,1,opt,name=Id,proto3" json:"Id,omitempty"`
	Name                 string   `protobuf:"bytes,2,opt,name=Name,proto3" json:"Name,omitempty"`
	Code                 string   `protobuf:"bytes,3,opt,name=Code,proto3" json:"Code,omitempty"`
	Description          string   `protobuf:"bytes,4,opt,name=Description,proto3" json:"Description,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UpdateOrderRequest) Reset()         { *m = UpdateOrderRequest{} }
func (m *UpdateOrderRequest) String() string { return proto.CompactTextString(m) }
func (*UpdateOrderRequest) ProtoMessage()    {}
func (*UpdateOrderRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_972d9d7dd8a32892, []int{6}
}

func (m *UpdateOrderRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdateOrderRequest.Unmarshal(m, b)
}
func (m *UpdateOrderRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdateOrderRequest.Marshal(b, m, deterministic)
}
func (m *UpdateOrderRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdateOrderRequest.Merge(m, src)
}
func (m *UpdateOrderRequest) XXX_Size() int {
	return xxx_messageInfo_UpdateOrderRequest.Size(m)
}
func (m *UpdateOrderRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdateOrderRequest.DiscardUnknown(m)
}

var xxx_messageInfo_UpdateOrderRequest proto.InternalMessageInfo

func (m *UpdateOrderRequest) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *UpdateOrderRequest) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *UpdateOrderRequest) GetCode() string {
	if m != nil {
		return m.Code
	}
	return ""
}

func (m *UpdateOrderRequest) GetDescription() string {
	if m != nil {
		return m.Description
	}
	return ""
}

// The response message to the update request.
// Returns the old values for the Order
type UpdateOrderReply struct {
	Order                *Order   `protobuf:"bytes,1,opt,name=order,proto3" json:"order,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UpdateOrderReply) Reset()         { *m = UpdateOrderReply{} }
func (m *UpdateOrderReply) String() string { return proto.CompactTextString(m) }
func (*UpdateOrderReply) ProtoMessage()    {}
func (*UpdateOrderReply) Descriptor() ([]byte, []int) {
	return fileDescriptor_972d9d7dd8a32892, []int{7}
}

func (m *UpdateOrderReply) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdateOrderReply.Unmarshal(m, b)
}
func (m *UpdateOrderReply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdateOrderReply.Marshal(b, m, deterministic)
}
func (m *UpdateOrderReply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdateOrderReply.Merge(m, src)
}
func (m *UpdateOrderReply) XXX_Size() int {
	return xxx_messageInfo_UpdateOrderReply.Size(m)
}
func (m *UpdateOrderReply) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdateOrderReply.DiscardUnknown(m)
}

var xxx_messageInfo_UpdateOrderReply proto.InternalMessageInfo

func (m *UpdateOrderReply) GetOrder() *Order {
	if m != nil {
		return m.Order
	}
	return nil
}

// The request message for the list activities request
type ListActivitiesRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ListActivitiesRequest) Reset()         { *m = ListActivitiesRequest{} }
func (m *ListActivitiesRequest) String() string { return proto.CompactTextString(m) }
func (*ListActivitiesRequest) ProtoMessage()    {}
func (*ListActivitiesRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_972d9d7dd8a32892, []int{8}
}

func (m *ListActivitiesRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListActivitiesRequest.Unmarshal(m, b)
}
func (m *ListActivitiesRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListActivitiesRequest.Marshal(b, m, deterministic)
}
func (m *ListActivitiesRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListActivitiesRequest.Merge(m, src)
}
func (m *ListActivitiesRequest) XXX_Size() int {
	return xxx_messageInfo_ListActivitiesRequest.Size(m)
}
func (m *ListActivitiesRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ListActivitiesRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ListActivitiesRequest proto.InternalMessageInfo

// The response message to the list activities request.
type ListActivitiesReply struct {
	Activities           []*Order `protobuf:"bytes,1,rep,name=activities,proto3" json:"activities,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ListActivitiesReply) Reset()         { *m = ListActivitiesReply{} }
func (m *ListActivitiesReply) String() string { return proto.CompactTextString(m) }
func (*ListActivitiesReply) ProtoMessage()    {}
func (*ListActivitiesReply) Descriptor() ([]byte, []int) {
	return fileDescriptor_972d9d7dd8a32892, []int{9}
}

func (m *ListActivitiesReply) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListActivitiesReply.Unmarshal(m, b)
}
func (m *ListActivitiesReply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListActivitiesReply.Marshal(b, m, deterministic)
}
func (m *ListActivitiesReply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListActivitiesReply.Merge(m, src)
}
func (m *ListActivitiesReply) XXX_Size() int {
	return xxx_messageInfo_ListActivitiesReply.Size(m)
}
func (m *ListActivitiesReply) XXX_DiscardUnknown() {
	xxx_messageInfo_ListActivitiesReply.DiscardUnknown(m)
}

var xxx_messageInfo_ListActivitiesReply proto.InternalMessageInfo

func (m *ListActivitiesReply) GetActivities() []*Order {
	if m != nil {
		return m.Activities
	}
	return nil
}

type Order struct {
	Id                   string   `protobuf:"bytes,1,opt,name=Id,proto3" json:"Id,omitempty"`
	Name                 string   `protobuf:"bytes,2,opt,name=Name,proto3" json:"Name,omitempty"`
	Code                 string   `protobuf:"bytes,3,opt,name=Code,proto3" json:"Code,omitempty"`
	Description          string   `protobuf:"bytes,4,opt,name=Description,proto3" json:"Description,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Order) Reset()         { *m = Order{} }
func (m *Order) String() string { return proto.CompactTextString(m) }
func (*Order) ProtoMessage()    {}
func (*Order) Descriptor() ([]byte, []int) {
	return fileDescriptor_972d9d7dd8a32892, []int{10}
}

func (m *Order) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Order.Unmarshal(m, b)
}
func (m *Order) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Order.Marshal(b, m, deterministic)
}
func (m *Order) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Order.Merge(m, src)
}
func (m *Order) XXX_Size() int {
	return xxx_messageInfo_Order.Size(m)
}
func (m *Order) XXX_DiscardUnknown() {
	xxx_messageInfo_Order.DiscardUnknown(m)
}

var xxx_messageInfo_Order proto.InternalMessageInfo

func (m *Order) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *Order) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Order) GetCode() string {
	if m != nil {
		return m.Code
	}
	return ""
}

func (m *Order) GetDescription() string {
	if m != nil {
		return m.Description
	}
	return ""
}

func init() {
	proto.RegisterType((*CreateOrderRequest)(nil), "ordercomm.CreateOrderRequest")
	proto.RegisterType((*CreateOrderReply)(nil), "ordercomm.CreateOrderReply")
	proto.RegisterType((*ReadOrderRequest)(nil), "ordercomm.ReadOrderRequest")
	proto.RegisterType((*ReadOrderReply)(nil), "ordercomm.ReadOrderReply")
	proto.RegisterType((*DeleteOrderRequest)(nil), "ordercomm.DeleteOrderRequest")
	proto.RegisterType((*DeleteOrderReply)(nil), "ordercomm.DeleteOrderReply")
	proto.RegisterType((*UpdateOrderRequest)(nil), "ordercomm.UpdateOrderRequest")
	proto.RegisterType((*UpdateOrderReply)(nil), "ordercomm.UpdateOrderReply")
	proto.RegisterType((*ListActivitiesRequest)(nil), "ordercomm.ListActivitiesRequest")
	proto.RegisterType((*ListActivitiesReply)(nil), "ordercomm.ListActivitiesReply")
	proto.RegisterType((*Order)(nil), "ordercomm.Order")
}

func init() { proto.RegisterFile("ordercomm/order.proto", fileDescriptor_972d9d7dd8a32892) }

var fileDescriptor_972d9d7dd8a32892 = []byte{
	// 377 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xb4, 0x54, 0x41, 0x4b, 0xf3, 0x40,
	0x10, 0x6d, 0x93, 0xb4, 0x7c, 0x9d, 0xf2, 0x95, 0x30, 0x52, 0x8c, 0x15, 0x25, 0x2c, 0x22, 0x9e,
	0xaa, 0xd4, 0x8b, 0xf4, 0xa4, 0xb6, 0x54, 0x2b, 0xa2, 0x50, 0xf1, 0xe2, 0x41, 0x88, 0xc9, 0x1e,
	0x02, 0x4d, 0x13, 0x93, 0xb5, 0xd0, 0x7f, 0xed, 0x4f, 0x90, 0xdd, 0x2d, 0x31, 0xbb, 0x49, 0x0b,
	0x3d, 0x78, 0x5b, 0xde, 0x3c, 0xde, 0xbc, 0x99, 0x79, 0x2c, 0x74, 0xe3, 0x34, 0xa0, 0xa9, 0x1f,
	0x47, 0xd1, 0xb9, 0x78, 0xf5, 0x93, 0x34, 0x66, 0x31, 0xb6, 0x72, 0x98, 0xbc, 0x03, 0x8e, 0x52,
	0xea, 0x31, 0xfa, 0xcc, 0xa1, 0x19, 0xfd, 0xfc, 0xa2, 0x19, 0x43, 0x04, 0xeb, 0xc9, 0x8b, 0xa8,
	0x53, 0x77, 0xeb, 0x67, 0xad, 0x99, 0x78, 0x73, 0x6c, 0x14, 0x07, 0xd4, 0x31, 0x24, 0xc6, 0xdf,
	0xe8, 0x42, 0x7b, 0x4c, 0x33, 0x3f, 0x0d, 0x13, 0x16, 0xc6, 0x0b, 0xc7, 0x14, 0xa5, 0x22, 0x44,
	0x08, 0xd8, 0x8a, 0x7e, 0x32, 0x5f, 0x61, 0x07, 0x8c, 0x69, 0xb0, 0xd6, 0x36, 0xa6, 0x01, 0xe7,
	0xcc, 0xa8, 0x17, 0x28, 0x0e, 0x74, 0xce, 0x15, 0x74, 0x0a, 0x1c, 0xae, 0x72, 0x0a, 0x0d, 0x31,
	0x86, 0x20, 0xb5, 0x07, 0x76, 0x3f, 0x1f, 0xaa, 0x2f, 0x59, 0xb2, 0x4c, 0x4e, 0x00, 0xc7, 0x74,
	0x4e, 0xb5, 0x09, 0x75, 0xfd, 0x21, 0xd8, 0x0a, 0x6b, 0x97, 0x0e, 0x0b, 0xc0, 0xd7, 0x24, 0xf0,
	0xb6, 0x77, 0xc8, 0x77, 0x6a, 0x54, 0xec, 0xd4, 0xdc, 0xbc, 0x53, 0xab, 0xbc, 0xd3, 0x21, 0xd8,
	0x4a, 0xbf, 0x5d, 0xbc, 0xee, 0x43, 0xf7, 0x31, 0xcc, 0xd8, 0x8d, 0xcf, 0xc2, 0x65, 0xc8, 0x42,
	0x9a, 0xad, 0xed, 0x92, 0x3b, 0xd8, 0xd3, 0x0b, 0x5c, 0xf7, 0x02, 0xc0, 0xcb, 0x21, 0xa7, 0xee,
	0x9a, 0x95, 0xe2, 0x05, 0x0e, 0xf1, 0xa0, 0x21, 0xc0, 0xbf, 0x5b, 0xc0, 0xe0, 0xdb, 0x80, 0x7f,
	0xa2, 0xc7, 0xcb, 0xd2, 0xc7, 0x09, 0x34, 0x65, 0xc2, 0xf0, 0xa8, 0xe0, 0xab, 0x1c, 0xea, 0xde,
	0xe1, 0xa6, 0x72, 0x32, 0x5f, 0x91, 0x1a, 0x5e, 0x83, 0xc5, 0x13, 0x86, 0x45, 0x9a, 0x1e, 0xcb,
	0xde, 0x41, 0x75, 0x51, 0x2a, 0x4c, 0xa0, 0x29, 0x33, 0xa4, 0x38, 0x29, 0x87, 0x4f, 0x71, 0xa2,
	0xa7, 0x4e, 0xea, 0xc8, 0xfb, 0x2a, 0x3a, 0xe5, 0x88, 0x29, 0x3a, 0x7a, 0x22, 0x48, 0x0d, 0x1f,
	0xc0, 0xe2, 0x27, 0x45, 0xb7, 0x40, 0xab, 0x3c, 0x7e, 0xef, 0x78, 0x0b, 0x43, 0x68, 0xdd, 0xfe,
	0xbf, 0x37, 0xdf, 0x7e, 0xbf, 0x8d, 0x8f, 0xa6, 0xf8, 0x48, 0x2e, 0x7f, 0x02, 0x00, 0x00, 0xff,
	0xff, 0x65, 0x32, 0x28, 0xc0, 0x61, 0x04, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// OrderSvcClient is the client API for OrderSvc service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type OrderSvcClient interface {
	// Creates a new order
	Create(ctx context.Context, in *CreateOrderRequest, opts ...grpc.CallOption) (*CreateOrderReply, error)
	// Reads an order
	Read(ctx context.Context, in *ReadOrderRequest, opts ...grpc.CallOption) (*ReadOrderReply, error)
	// Delete an order
	Delete(ctx context.Context, in *DeleteOrderRequest, opts ...grpc.CallOption) (*DeleteOrderReply, error)
	// Update an order
	Update(ctx context.Context, in *UpdateOrderRequest, opts ...grpc.CallOption) (*UpdateOrderReply, error)
	// List an order
	List(ctx context.Context, in *ListActivitiesRequest, opts ...grpc.CallOption) (*ListActivitiesReply, error)
}

type orderSvcClient struct {
	cc *grpc.ClientConn
}

func NewOrderSvcClient(cc *grpc.ClientConn) OrderSvcClient {
	return &orderSvcClient{cc}
}

func (c *orderSvcClient) Create(ctx context.Context, in *CreateOrderRequest, opts ...grpc.CallOption) (*CreateOrderReply, error) {
	out := new(CreateOrderReply)
	err := c.cc.Invoke(ctx, "/ordercomm.OrderSvc/Create", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *orderSvcClient) Read(ctx context.Context, in *ReadOrderRequest, opts ...grpc.CallOption) (*ReadOrderReply, error) {
	out := new(ReadOrderReply)
	err := c.cc.Invoke(ctx, "/ordercomm.OrderSvc/Read", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *orderSvcClient) Delete(ctx context.Context, in *DeleteOrderRequest, opts ...grpc.CallOption) (*DeleteOrderReply, error) {
	out := new(DeleteOrderReply)
	err := c.cc.Invoke(ctx, "/ordercomm.OrderSvc/Delete", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *orderSvcClient) Update(ctx context.Context, in *UpdateOrderRequest, opts ...grpc.CallOption) (*UpdateOrderReply, error) {
	out := new(UpdateOrderReply)
	err := c.cc.Invoke(ctx, "/ordercomm.OrderSvc/Update", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *orderSvcClient) List(ctx context.Context, in *ListActivitiesRequest, opts ...grpc.CallOption) (*ListActivitiesReply, error) {
	out := new(ListActivitiesReply)
	err := c.cc.Invoke(ctx, "/ordercomm.OrderSvc/List", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// OrderSvcServer is the server API for OrderSvc service.
type OrderSvcServer interface {
	// Creates a new order
	Create(context.Context, *CreateOrderRequest) (*CreateOrderReply, error)
	// Reads an order
	Read(context.Context, *ReadOrderRequest) (*ReadOrderReply, error)
	// Delete an order
	Delete(context.Context, *DeleteOrderRequest) (*DeleteOrderReply, error)
	// Update an order
	Update(context.Context, *UpdateOrderRequest) (*UpdateOrderReply, error)
	// List an order
	List(context.Context, *ListActivitiesRequest) (*ListActivitiesReply, error)
}

// UnimplementedOrderSvcServer can be embedded to have forward compatible implementations.
type UnimplementedOrderSvcServer struct {
}

func (*UnimplementedOrderSvcServer) Create(ctx context.Context, req *CreateOrderRequest) (*CreateOrderReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Create not implemented")
}
func (*UnimplementedOrderSvcServer) Read(ctx context.Context, req *ReadOrderRequest) (*ReadOrderReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Read not implemented")
}
func (*UnimplementedOrderSvcServer) Delete(ctx context.Context, req *DeleteOrderRequest) (*DeleteOrderReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Delete not implemented")
}
func (*UnimplementedOrderSvcServer) Update(ctx context.Context, req *UpdateOrderRequest) (*UpdateOrderReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Update not implemented")
}
func (*UnimplementedOrderSvcServer) List(ctx context.Context, req *ListActivitiesRequest) (*ListActivitiesReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method List not implemented")
}

func RegisterOrderSvcServer(s *grpc.Server, srv OrderSvcServer) {
	s.RegisterService(&_OrderSvc_serviceDesc, srv)
}

func _OrderSvc_Create_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateOrderRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OrderSvcServer).Create(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/ordercomm.OrderSvc/Create",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OrderSvcServer).Create(ctx, req.(*CreateOrderRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _OrderSvc_Read_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ReadOrderRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OrderSvcServer).Read(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/ordercomm.OrderSvc/Read",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OrderSvcServer).Read(ctx, req.(*ReadOrderRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _OrderSvc_Delete_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteOrderRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OrderSvcServer).Delete(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/ordercomm.OrderSvc/Delete",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OrderSvcServer).Delete(ctx, req.(*DeleteOrderRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _OrderSvc_Update_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateOrderRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OrderSvcServer).Update(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/ordercomm.OrderSvc/Update",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OrderSvcServer).Update(ctx, req.(*UpdateOrderRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _OrderSvc_List_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListActivitiesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OrderSvcServer).List(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/ordercomm.OrderSvc/List",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OrderSvcServer).List(ctx, req.(*ListActivitiesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _OrderSvc_serviceDesc = grpc.ServiceDesc{
	ServiceName: "ordercomm.OrderSvc",
	HandlerType: (*OrderSvcServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Create",
			Handler:    _OrderSvc_Create_Handler,
		},
		{
			MethodName: "Read",
			Handler:    _OrderSvc_Read_Handler,
		},
		{
			MethodName: "Delete",
			Handler:    _OrderSvc_Delete_Handler,
		},
		{
			MethodName: "Update",
			Handler:    _OrderSvc_Update_Handler,
		},
		{
			MethodName: "List",
			Handler:    _OrderSvc_List_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "ordercomm/order.proto",
}
